[build]
command = "npm install --legacy-peer-deps && npm run build"
publish = "dist"

[build.environment]
VITE_APP_EMAILJS_SERVICE_ID = "service_pdex8yf"
VITE_APP_EMAILJS_TEMPLATE_ID = "template_bapz7qd"
VITE_APP_EMAILJS_PUBLIC_KEY = "fAtPoklJObIbvCepl"
